// Local JSON Database Fallback (if Supabase is not set up)
// This allows the site to work without backend initially

export const defaultData = {
  hero: {
    id: '1',
    heading: 'Hello, I\'m REDOANUZZAMAN',
    subheading: 'Creative Designer & AI Automation Expert',
    bio: 'I\'m a passionate and dedicated creative designer specializing in n8n, LangChain, LangFlow, Zapier, and website development—turning ideas into seamless digital experiences.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  about: {
    id: '1',
    title: 'About Me',
    description: 'With years of experience in automation and AI, I help businesses streamline their workflows and implement cutting-edge solutions. My expertise spans across multiple automation platforms and AI technologies, allowing me to create custom solutions tailored to each client\'s unique needs.',
    image_url: 'https://redoan.dev/wp-content/uploads/2025/09/Weixin-Image_20250921025540_83_37-1.jpg',
    image_frame: 'rounded' as const,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  skills: [
    { id: '1', name: 'n8n', icon: 'https://redoan.dev/wp-content/uploads/2025/09/n8n-color-1.png', level: 95, order: 1, created_at: new Date().toISOString() },
    { id: '2', name: 'Make', icon: 'https://redoan.dev/wp-content/uploads/2025/09/make-color.png', level: 90, order: 2, created_at: new Date().toISOString() },
    { id: '3', name: 'Zapier', icon: 'https://redoan.dev/wp-content/uploads/2025/09/51813691-935f4580-2285-11e9-9ac7-7e5fe92e3ee9.png', level: 92, order: 3, created_at: new Date().toISOString() },
    { id: '4', name: 'LangChain', icon: 'https://redoan.dev/wp-content/uploads/2025/09/langchain-color.png', level: 88, order: 4, created_at: new Date().toISOString() },
    { id: '5', name: 'LangFlow', icon: 'https://redoan.dev/wp-content/uploads/2025/09/85702467.png', level: 85, order: 5, created_at: new Date().toISOString() },
    { id: '6', name: 'API Integration', icon: 'https://redoan.dev/wp-content/uploads/2025/09/api.png', level: 93, order: 6, created_at: new Date().toISOString() },
    { id: '7', name: 'WordPress', icon: 'https://redoan.dev/wp-content/uploads/2025/09/wordpress.png', level: 90, order: 7, created_at: new Date().toISOString() },
    { id: '8', name: 'Website Development', icon: 'FaCode', level: 92, order: 8, created_at: new Date().toISOString() },
  ],
  projects: [
    {
      id: '1',
      title: 'E-commerce Automation System',
      description: 'Built a complete automation system for order processing and inventory management using n8n',
      image_url: '/images/project1.jpg',
      tech_tags: ['n8n', 'API', 'Automation'],
      project_url: '#',
      github_url: '#',
      order: 1,
      featured: true,
      created_at: new Date().toISOString(),
    },
    {
      id: '2',
      title: 'AI Customer Support Bot',
      description: 'Developed an intelligent chatbot using LangChain and GPT-4 for automated customer support',
      image_url: '/images/project2.jpg',
      tech_tags: ['LangChain', 'GPT-4', 'AI'],
      project_url: '#',
      github_url: '#',
      order: 2,
      featured: true,
      created_at: new Date().toISOString(),
    },
    {
      id: '3',
      title: 'Multi-Platform Integration',
      description: 'Created seamless integrations between 10+ platforms using Zapier and custom APIs',
      image_url: '/images/project3.jpg',
      tech_tags: ['Zapier', 'API', 'Integration'],
      project_url: '#',
      github_url: '#',
      order: 3,
      featured: true,
      created_at: new Date().toISOString(),
    },
    {
      id: '4',
      title: 'Document Processing AI',
      description: 'Built an AI-powered document analysis tool using LangFlow and custom NLP models',
      image_url: '/images/project4.jpg',
      tech_tags: ['LangFlow', 'NLP', 'AI'],
      project_url: '#',
      github_url: '#',
      order: 4,
      featured: false,
      created_at: new Date().toISOString(),
    },
    {
      id: '5',
      title: 'Business Workflow Automation',
      description: 'Automated complex business workflows reducing manual work by 80%',
      image_url: '/images/project5.jpg',
      tech_tags: ['n8n', 'Automation', 'Business'],
      project_url: '#',
      github_url: '#',
      order: 5,
      featured: false,
      created_at: new Date().toISOString(),
    },
    {
      id: '6',
      title: 'SaaS Platform Development',
      description: 'Full-stack SaaS platform with automated onboarding and AI features',
      image_url: '/images/project6.jpg',
      tech_tags: ['Next.js', 'AI', 'SaaS'],
      project_url: '#',
      github_url: '#',
      order: 6,
      featured: false,
      created_at: new Date().toISOString(),
    },
    {
      id: '7',
      title: 'Social Media Post Project',
      description: 'Designed social media post graphics and reusable templates for campaigns.',
      image_url: 'https://redoan.dev/wp-content/uploads/2025/09/Screenshot-2025-09-24-152604.png',
      tech_tags: ['Design', 'Social Media', 'Graphics'],
      project_url: '#',
      github_url: '#',
      order: 7,
      featured: false,
      created_at: new Date().toISOString(),
    },
  ],
  services: [
    {
      id: '1',
      name: 'Starter',
      type: 'starter' as const,
      price: '$499',
      description: 'Perfect for small businesses starting with automation',
      features: [
        'Basic automations',
        'Simple workflows',
        '1 integration',
        'Email support',
        '2 revisions',
      ],
      order: 1,
      created_at: new Date().toISOString(),
    },
    {
      id: '2',
      name: 'Professional',
      type: 'professional' as const,
      price: '$1,499',
      description: 'Advanced automation for growing businesses',
      features: [
        'Advanced automations',
        'Multi-step workflows (n8n, LangChain, Zapier)',
        'API integrations',
        'Dashboard setup',
        'Priority support',
        '5 revisions',
        'Documentation',
      ],
      order: 2,
      created_at: new Date().toISOString(),
    },
    {
      id: '3',
      name: 'Premium',
      type: 'premium' as const,
      price: '$3,999',
      description: 'Complete enterprise automation solution',
      features: [
        'Full business automation',
        'Custom AI agents (LangChain, LangFlow)',
        'Database + API connection',
        'Multi-platform workflows',
        'Monitoring + maintenance',
        '1-1 consultation',
        'Unlimited revisions',
        'Training sessions',
        '3 months support',
      ],
      order: 3,
      created_at: new Date().toISOString(),
    },
  ],
  testimonials: [
    {
      id: '1',
      name: 'John Doe',
      role: 'CEO',
      company: 'Tech Startup Inc.',
      content: 'Working with Redoan was a game-changer for our business. The automation solutions saved us countless hours.',
      image_url: '/images/testimonial1.jpg',
      rating: 5,
      order: 1,
      created_at: new Date().toISOString(),
    },
    {
      id: '2',
      name: 'Jane Smith',
      role: 'Operations Manager',
      company: 'E-commerce Co.',
      content: 'Excellent work! The AI chatbot has improved our customer satisfaction by 40%.',
      image_url: '/images/testimonial2.jpg',
      rating: 5,
      order: 2,
      created_at: new Date().toISOString(),
    },
    {
      id: '3',
      name: 'Michael Brown',
      role: 'Founder',
      company: 'Digital Agency',
      content: 'Professional, reliable, and incredibly skilled. Highly recommend!',
      image_url: '/images/testimonial3.jpg',
      rating: 5,
      order: 3,
      created_at: new Date().toISOString(),
    },
  ],
  settings: {
    id: '1',
    site_title: 'REDOANUZZAMAN - Portfolio',
    site_description: 'Creative Designer & AI Automation Expert',
    contact_email: 'contact@redoanuzzaman.com',
    contact_phone: '+1 (555) 123-4567',
    contact_location: 'Your City, Country',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
      twitter: 'https://twitter.com',
      email: 'mailto:contact@redoanuzzaman.com',
    },
    logo_url: '/logo.png',
    primary_color: '#667eea',
    secondary_color: '#764ba2',
    footer_text: '© {year} REDOANUZZAMAN. Made with ❤️ by REDOANUZZAMAN',
    updated_at: new Date().toISOString(),
  },
};
